import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import OfferCardContainer from "~/modules/offers/components/OfferCardContainer";
import { ResponseExperienceOffers } from "~/modules/offers/types/response";
import fetcher from "~/utils/fetcher";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, error } = useSWR<ResponseExperienceOffers>(
    "/api/offers",
    fetcher
  );

  if (!data) return null;

  const { popular_offers } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper">
        {popular_offers.map((container) => {
          return (
            <OfferCardContainer key={container.title} container={container} />
          );
        })}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
